import type { ModelInfo } from '@/types/chat'

// 模型列表：来自硅基流动实测（可用对话模型），free 标记依据官方价格页
export const MODEL_LIST: ModelInfo[] = [
  { id: 'PaddlePaddle/PaddleOCR-VL-1.5', name: 'PaddleOCR-VL-1.5', free: true, vision: true },
  { id: 'THUDM/GLM-Z1-9B-0414', name: 'GLM-Z1-9B', free: true },
  { id: 'tencent/Hunyuan-MT-7B', name: 'Hunyuan-MT-7B', free: true },
  { id: 'ByteDance-Seed/Seed-OSS-36B-Instruct', name: 'Seed-OSS-36B-Instruct', free: false },
  { id: 'LoRA/Qwen/Qwen2.5-14B-Instruct', name: 'Qwen2.5-14B-Instruct (LoRA)', free: false },
  { id: 'LoRA/Qwen/Qwen2.5-32B-Instruct', name: 'Qwen2.5-32B-Instruct (LoRA)', free: false },
  { id: 'LoRA/Qwen/Qwen2.5-72B-Instruct', name: 'Qwen2.5-72B-Instruct (LoRA)', free: false },
  { id: 'LoRA/Qwen/Qwen2.5-7B-Instruct', name: 'Qwen2.5-7B-Instruct (LoRA)', free: false },
  { id: 'MiniMaxAI/MiniMax-M2.5', name: 'MiniMax-M2.5', free: false },
  { id: 'Pro/MiniMaxAI/MiniMax-M2.5', name: 'MiniMax-M2.5 (Pro)', free: false },
  { id: 'Pro/Qwen/Qwen2.5-7B-Instruct', name: 'Qwen2.5-7B-Instruct (Pro)', free: false },
  { id: 'Pro/deepseek-ai/DeepSeek-R1', name: 'DeepSeek-R1 (Pro)', free: false },
  { id: 'Pro/deepseek-ai/DeepSeek-V3', name: 'DeepSeek-V3 (Pro)', free: false },
  { id: 'Pro/deepseek-ai/DeepSeek-V3.1-Terminus', name: 'DeepSeek-V3.1-Terminus (Pro)', free: false },
  { id: 'Pro/deepseek-ai/DeepSeek-V3.2', name: 'DeepSeek-V3.2 (Pro)', free: false },
  { id: 'Pro/moonshotai/Kimi-K2.6', name: 'Kimi-K2.6 (Pro)', free: false },
  { id: 'Pro/zai-org/GLM-5.1', name: 'GLM-5.1 (Pro)', free: false },
  { id: 'Qwen/Qwen2.5-14B-Instruct', name: 'Qwen2.5-14B-Instruct', free: false },
  { id: 'Qwen/Qwen2.5-32B-Instruct', name: 'Qwen2.5-32B-Instruct', free: false },
  { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen2.5-72B-Instruct', free: false },
  { id: 'Qwen/Qwen2.5-72B-Instruct-128K', name: 'Qwen2.5-72B-Instruct-128K', free: false },
  { id: 'Qwen/Qwen2.5-7B-Instruct', name: 'Qwen2.5-7B-Instruct', free: false },
  { id: 'Qwen/Qwen3-14B', name: 'Qwen3-14B', free: false },
  { id: 'Qwen/Qwen3-30B-A3B-Instruct-2507', name: 'Qwen3-30B-A3B-Instruct', free: false },
  { id: 'Qwen/Qwen3-32B', name: 'Qwen3-32B', free: false },
  { id: 'Qwen/Qwen3-8B', name: 'Qwen3-8B', free: false },
  { id: 'Qwen/Qwen3-Coder-30B-A3B-Instruct', name: 'Qwen3-Coder-30B-A3B-Instruct', free: false },
  { id: 'Qwen/Qwen3-Omni-30B-A3B-Captioner', name: 'Qwen3-Omni-30B-A3B-Captioner', free: false, vision: true },
  { id: 'Qwen/Qwen3-Omni-30B-A3B-Instruct', name: 'Qwen3-Omni-30B-A3B-Instruct', free: false, vision: true },
  { id: 'Qwen/Qwen3-Omni-30B-A3B-Thinking', name: 'Qwen3-Omni-30B-A3B-Thinking', free: false, vision: true },
  { id: 'Qwen/Qwen3-VL-30B-A3B-Instruct', name: 'Qwen3-VL-30B-A3B-Instruct', free: false, vision: true },
  { id: 'Qwen/Qwen3-VL-30B-A3B-Thinking', name: 'Qwen3-VL-30B-A3B-Thinking', free: false, vision: true },
  { id: 'Qwen/Qwen3-VL-32B-Instruct', name: 'Qwen3-VL-32B-Instruct', free: false, vision: true },
  { id: 'Qwen/Qwen3-VL-32B-Thinking', name: 'Qwen3-VL-32B-Thinking', free: false, vision: true },
  { id: 'Qwen/Qwen3-VL-8B-Instruct', name: 'Qwen3-VL-8B-Instruct', free: false, vision: true },
  { id: 'Qwen/Qwen3-VL-8B-Thinking', name: 'Qwen3-VL-8B-Thinking', free: false, vision: true },
  { id: 'Qwen/Qwen3.5-122B-A10B', name: 'Qwen3.5-122B-A10B', free: false },
  { id: 'Qwen/Qwen3.5-27B', name: 'Qwen3.5-27B', free: false },
  { id: 'Qwen/Qwen3.5-35B-A3B', name: 'Qwen3.5-35B-A3B', free: false },
  { id: 'Qwen/Qwen3.5-397B-A17B', name: 'Qwen3.5-397B-A17B', free: false },
  { id: 'Qwen/Qwen3.5-4B', name: 'Qwen3.5-4B', free: false },
  { id: 'Qwen/Qwen3.5-9B', name: 'Qwen3.5-9B', free: false },
  { id: 'Qwen/Qwen3.6-27B', name: 'Qwen3.6-27B', free: false },
  { id: 'Qwen/Qwen3.6-35B-A3B', name: 'Qwen3.6-35B-A3B', free: false },
  { id: 'THUDM/GLM-4-32B-0414', name: 'GLM-4-32B', free: false },
  { id: 'THUDM/GLM-4-9B-0414', name: 'GLM-4-9B', free: false },
  { id: 'deepseek-ai/DeepSeek-OCR', name: 'DeepSeek-OCR', free: false, vision: true },
  { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek-R1', free: false },
  { id: 'deepseek-ai/DeepSeek-R1-0528-Qwen3-8B', name: 'DeepSeek-R1-0528-Qwen3-8B', free: false },
  { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek-V3', free: false },
  { id: 'deepseek-ai/DeepSeek-V3.1-Terminus', name: 'DeepSeek-V3.1-Terminus', free: false },
  { id: 'deepseek-ai/DeepSeek-V3.2', name: 'DeepSeek-V3.2', free: false },
  { id: 'deepseek-ai/DeepSeek-V4-Flash', name: 'DeepSeek-V4-Flash', free: false },
  { id: 'deepseek-ai/DeepSeek-V4-Pro', name: 'DeepSeek-V4-Pro', free: false },
  { id: 'inclusionAI/Ling-flash-2.0', name: 'Ling-flash-2.0', free: false },
  { id: 'inclusionAI/Ling-mini-2.0', name: 'Ling-mini-2.0', free: false },
  { id: 'meituan-longcat/LongCat-2.0', name: 'LongCat-2.0', free: false },
  { id: 'moonshotai/Kimi-K2.7-Code', name: 'Kimi-K2.7-Code', free: false },
  { id: 'nex-agi/Nex-N2-Pro', name: 'Nex-N2-Pro', free: false },
  { id: 'stepfun-ai/Step-3.5-Flash', name: 'Step-3.5-Flash', free: false },
  { id: 'tencent/Hunyuan-A13B-Instruct', name: 'Hunyuan-A13B-Instruct', free: false },
  { id: 'zai-org/GLM-4.5-Air', name: 'GLM-4.5-Air', free: false },
  { id: 'zai-org/GLM-4.5V', name: 'GLM-4.5V', free: false, vision: true },
  { id: 'zai-org/GLM-5.2', name: 'GLM-5.2', free: false },
]
